---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      include: scope
      prefix: fix(gha)

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(docker)

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(bundler)

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(npm+docs)

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-requirements:
        patterns:
          - "*"
    commit-message:
      prefix: fix(pip prod)
      prefix-development: fix(pip dev)
      include: scope
